# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 코드자이저's 기술 블로그
email: codegizer.kim@gmail.com
description: 

paginate:	5

permalink: /:year/:month/:day/:title.html  
url: "http://codegizer.me" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: codegizer_kim
github_username:  codegizer

# tracking & ad code
fb_app_id: "489041618160466"
g-analytics: UA-169288078-1

# DISQUS
comments: true
# other options

# Build settings
#markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-toc

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfijendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
